import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import QueryClientProvider from "./QueryClientProvider";
import ContextProvider from "./context/contextProvider";
import { Toaster } from "@/components/ui/toaster";
import SearchContextProvider from "./context/searchContextProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Providers from "@/components/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <QueryClientProvider>
          <ContextProvider>
            <SearchContextProvider>
              <AntdRegistry>
                <Providers>
                  <Header />
                  {children}
                  <Footer />
                </Providers>

                <Toaster />
              </AntdRegistry>
            </SearchContextProvider>
          </ContextProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
